SELECT DISTINCT I.ASIGNATURA
FROM IMPARTIR I
WHERE I.PROFESOR IN 
(SELECT P.ID    
FROM PROFESORES P, IMPARTIR IM
WHERE P.ID = IM.PROFESOR AND IM.ASIGNATURA = 112);

SELECT D.NOMBRE
FROM DEPARTAMENTOS D
WHERE NOT EXISTS
(SELECT * 
FROM ASIGNATURAS A
WHERE A.CREDITOS > 6 AND D.CODIGO = A.DEPARTAMENTO);

SELECT A.DNI
FROM ALUMNOS A
WHERE A.DNI IN
(SELECT M.ALUMNO
FROM MATRICULAR M
WHERE M.ASIGNATURA IN 
(SELECT I.ASIGNATURA
FROM IMPARTIR I, PROFESORES P
WHERE I.PROFESOR = P.ID AND P.ANTIGUEDAD <= ALL
(SELECT ANTIGUEDAD FROM PROFESORES)));

SELECT P1.ID "Profesor 1", P2.ID "Profesor 2"
FROM PROFESORES P1, PROFESORES P2
WHERE P1.ID < P2.ID AND NOT EXISTS 
(SELECT *
FROM MATRICULAR M1
WHERE (M1.ASIGNATURA, M1.GRUPO, M1.CURSO) IN 
(SELECT ASIGNATURA, GRUPO, CURSO
FROM IMPARTIR
WHERE PROFESOR = P1.ID)
AND M1.ALUMNO NOT IN
(SELECT M2.ALUMNO
FROM MATRICULAR M2
WHERE (M2.ASIGNATURA, M2.GRUPO, M2.CURSO) IN 
(SELECT ASIGNATURA, GRUPO, CURSO
FROM IMPARTIR
WHERE PROFESOR = P2.ID)));
