SELECT AL.NOMBRE, M.CALIFICACION
FROM ALUMNOS AL, MATRICULAR M, ASIGNATURAS ASIG
WHERE AL.DNI = M.ALUMNO AND M.ASIGNATURA = ASIG.CODIGO AND M.CALIFICACION IN ('AP', 'NT', 'SB', 'MH') AND ASIG.NOMBRE = 'Bases de Datos';

SELECT AL.NOMBRE, ASIG.NOMBRE, M.GRUPO
FROM ALUMNOS AL, MATRICULAR M, ASIGNATURAS ASIG
WHERE AL.DNI = M.ALUMNO AND M.ASIGNATURA = ASIG.CODIGO;

SELECT AL.NOMBRE "Alumno", ASIG.NOMBRE "Asigntura", M.CALIFICACION "Calificacion", P.NOMBRE "Profesor"
FROM ALUMNOS AL, MATRICULAR M, ASIGNATURAS ASIG, PROFESORES P, IMPARTIR I
WHERE AL.DNI = M.ALUMNO AND M.ASIGNATURA = ASIG.CODIGO AND M.CALIFICACION IN ('AP', 'NT', 'SB', 'MH')
    AND P.ID = I.PROFESOR AND I.ASIGNATURA = M.ASIGNATURA AND I.GRUPO = M.GRUPO AND I.CURSO = M.CURSO;
    
SELECT PROF.*, DIR.*
FROM PROFESORES PROF LEFT OUTER JOIN PROFESORES DIR ON PROF.DIRECTOR_TESIS = DIR.ID;