--1
SELECT AL.GENERO, ROUND(AVG(DECODE(M.CALIFICACION, 'MH', 10, 'SB', 9, 'NT', 7, 'AP', 5, 'SP', 0, 0)), 2) "MEDIA"
FROM ALUMNOS AL, MATRICULAR M
WHERE AL.DNI = M.ALUMNO AND M.CURSO = '21/22'
GROUP BY AL.GENERO;

--2
SELECT ASIG.CODIGO, ROUND(AVG(DECODE(M.CALIFICACION, 'MH', 10, 'SB', 9, 'NT', 7, 'AP', 5, 'SP', 0, 0)), 2)
FROM MATRICULAR M, ASIGNATURAS ASIG
WHERE M.ASIGNATURA = ASIG.CODIGO
GROUP BY ASIG.CODIGO
HAVING MIN(DECODE(M.CALIFICACION, 'MH', 10, 'SB', 9, 'NT', 7, 'AP', 5, 'SP', 0, 0)) > 4;

--3
SELECT P.ID, NVL(SUM(I.CARGA_CREDITOS), 0) "CREDITOS TOTALES", p.departamento
FROM PROFESORES P, IMPARTIR I
WHERE P.ID = I.PROFESOR
GROUP BY P.ID, P.DEPARTAMENTO
ORDER BY P.DEPARTAMENTO;

--4
SELECT UPPER(SUBSTR(M.NOMBRE, 1, 1)) "Primera letra", SUM(M.HOMBRES) + SUM(M.MUJERES) "Poblacion total", MIN(M.HOMBRES+M.MUJERES) "Habitantes minimos", MAX(M.HOMBRES+M.MUJERES) "Habitantes maximos"
FROM MUNICIPIO M
GROUP BY UPPER(SUBSTR(M.NOMBRE, 1, 1));

--5
SELECT UPPER(SUBSTR(M.NOMBRE, 1, 1)) "Primera letra", SUM(M.HOMBRES) + SUM(M.MUJERES) "Poblacion total", MIN(M.HOMBRES+M.MUJERES) "Habitantes minimos", MAX(M.HOMBRES+M.MUJERES) "Habitantes maximos"
FROM MUNICIPIO M
GROUP BY UPPER(SUBSTR(M.NOMBRE, 1, 1))
HAVING SUM(M.HOMBRES) + SUM(M.MUJERES) < 10000;

--6
SELECT *
FROM PROFESORES P
WHERE (P.DEPARTAMENTO, P.ANTIGUEDAD) IN
(SELECT DEPARTAMENTO, MIN(ANTIGUEDAD)
FROM PROFESORES
GROUP BY DEPARTAMENTO);

--7
SELECT *
FROM 
(SELECT AL.DNI, COUNT(*) "ASIGNATURAS APROBADAS", ROUND(AVG(DECODE(M.CALIFICACION, 'MH', 10, 'SB', 9, 'NT', 7, 'AP', 5, 'SP', 0, 0)), 2) "MEDIA"
FROM ALUMNOS AL, 
(SELECT ALUMNO, CALIFICACION
FROM MATRICULAR
WHERE DECODE(CALIFICACION, 'MH', 10, 'SB', 9, 'NT', 7, 'AP', 5, 'SP', 0, 0) >= 5) M
WHERE AL.DNI = M.ALUMNO
GROUP BY AL.DNI
ORDER BY "ASIGNATURAS APROBADAS" DESC)
WHERE ROWNUM <= 3;

--8
SELECT AL.DNI, AL.NOMBRE || ' ' || AL.APELLIDO1 || ' ' || AL.APELLIDO2 "NOMBRE COMPLETO", AL.EMAIL, TRUNC(MONTHS_BETWEEN(SYSDATE, AL.FECHA_NACIMIENTO)/12, 0) "EDAD"
FROM ALUMNOS AL, MATRICULAR M,
(SELECT *
FROM    
(SELECT COUNT(*) "N_MATRICULADOS", ASIGNATURA
FROM MATRICULAR
GROUP BY ASIGNATURA
ORDER BY "N_MATRICULADOS" DESC)
WHERE ROWNUM < 2) N
WHERE AL.DNI = M.ALUMNO AND M.ASIGNATURA = N.ASIGNATURA;

--9
SELECT NVL(APROB.APROBADOS, 0)/TOTAL.TOTALES "TASA DE RENDIMIENTO", TOTAL.CURSO
FROM
(SELECT SUM(M.CREDITOS) "APROBADOS", M.CURSO
FROM 
(SELECT ASIG.CREDITOS, MAT.CALIFICACION, MAT.CURSO
FROM MATRICULAR MAT, ASIGNATURAS ASIG
WHERE MAT.ASIGNATURA = ASIG.CODIGO) M
WHERE DECODE(M.CALIFICACION, 'MH', 10, 'SB', 9, 'NT', 7, 'AP', 5, 'SP', 0, 0) >= 5
GROUP BY M.CURSO) APROB
RIGHT OUTER JOIN
(SELECT SUM(M2.CREDITOS) "TOTALES", M2.CURSO
FROM 
(SELECT ASIG2.CREDITOS, MAT2.CALIFICACION, MAT2.CURSO
FROM MATRICULAR MAT2, ASIGNATURAS ASIG2
WHERE MAT2.ASIGNATURA = ASIG2.CODIGO) M2
GROUP BY M2.CURSO) TOTAL
ON (APROB.CURSO = TOTAL.CURSO);
