--1
SELECT COUNT(*) "NUMERO PROFESORES", D.NOMBRE "NOMBRE DEL DEPARTAMENTO"
FROM PROFESORES P, DEPARTAMENTOS D
WHERE P.DEPARTAMENTO = D.CODIGO
GROUP BY P.DEPARTAMENTO, D.NOMBRE;

--2
SELECT D.NOMBRE "NOMBRE DEL DEPARTAMENTO", SUM(ASIG.CREDITOS) "CREDITOS TOTALES"
FROM DEPARTAMENTOS D, ASIGNATURAS ASIG
WHERE D.CODIGO = ASIG.DEPARTAMENTO
GROUP BY ASIG.DEPARTAMENTO, D.NOMBRE;

--3
SELECT M.CURSO, COUNT(DISTINCT M.ALUMNO) "NUMERO ALUMNOS"
FROM MATRICULAR M
GROUP BY M.CURSO;

--4
SELECT P.DESPACHO, SUM(I.CARGA_CREDITOS)
FROM PROFESORES P, IMPARTIR I
WHERE P.ID = I.PROFESOR AND P.DESPACHO IS NOT NULL
GROUP BY P.DESPACHO, I.PROFESOR;

--5
SELECT TOTAL.CODIGO, ROUND(NVL(FEM.NUM, 0)/TOTAL.NUM, 2)  "PORCENTAJE MUJERES"
FROM 
(SELECT COUNT(*) "NUM", M.ASIGNATURA "CODIGO"
FROM MATRICULAR M, ALUMNOS AL
WHERE M.ALUMNO = AL.DNI
GROUP BY M.ASIGNATURA) TOTAL LEFT OUTER JOIN
(SELECT COUNT(*) "NUM", M1.ASIGNATURA "CODIGO"
FROM MATRICULAR M1, ALUMNOS AL1
WHERE M1.ALUMNO = AL1.DNI AND AL1.GENERO = 'FEM'
GROUP BY M1.ASIGNATURA) FEM ON (TOTAL.CODIGO = FEM.CODIGO);

--6
SELECT P.NOMBRE, SUM(M.HOMBRES + M.MUJERES) "POBLACION"
FROM MUNICIPIO M, PROVINCIA P
WHERE M.CPRO = P.CODIGO
GROUP BY M.CPRO, P.NOMBRE;

--7 
SELECT D.DEPARTAMENTO, NOMBRE, APELLIDO1, APELLIDO2
FROM PROFESORES,
(SELECT P.DEPARTAMENTO, MIN(P.FECHA_NACIMIENTO) "F"
FROM PROFESORES P
GROUP BY P.DEPARTAMENTO) D
WHERE FECHA_NACIMIENTO = D.F;

--8
SELECT MAT.ALUMNO, A.NOMBRE
FROM MATRICULAR MAT, ASIGNATURAS A
WHERE MAT.ASIGNATURA = A.CODIGO
AND (MAT.ALUMNO, A.CREDITOS) IN
    (SELECT M.ALUMNO, MAX(ASIG.CREDITOS)
    FROM MATRICULAR M, ASIGNATURAS ASIG
    WHERE M.ASIGNATURA = ASIG.CODIGO
    GROUP BY M.ALUMNO);

--9
SELECT D.DEPARTAMENTO, NOMBRE, APELLIDO1, APELLIDO2
FROM PROFESORES,
(SELECT P.DEPARTAMENTO, MIN(P.ANTIGUEDAD) "F"
FROM PROFESORES P
GROUP BY P.DEPARTAMENTO) D
WHERE ANTIGUEDAD = D.F;

--10
SELECT ASIG1.DEPARTAMENTO, ASIG1.NOMBRE
FROM ASIGNATURAS ASIG1
WHERE ASIG1.CREDITOS <= ALL
(SELECT ASIG2.CREDITOS
FROM ASIGNATURAS ASIG2
WHERE ASIG2.CREDITOS IS NOT NULL
AND ASIG2.DEPARTAMENTO = ASIG1.DEPARTAMENTO);

--11
SELECT M1.ASIGNATURA, AL1.*
FROM ALUMNOS AL1, MATRICULAR M1
WHERE M1.ALUMNO = AL1.DNI AND M1.CURSO = '20/21' 
AND (M1.ASIGNATURA, AL1.FECHA_NACIMIENTO) IN
    (SELECT M.ASIGNATURA, MAX(AL.FECHA_NACIMIENTO)
    FROM MATRICULAR M, ALUMNOS AL
    WHERE AL.DNI = M.ALUMNO AND M.CURSO = '20/21'
    GROUP BY M.ASIGNATURA);

--12
SELECT P.ID, P.NOMBRE, P.APELLIDO1, SUM(NVL(I.CARGA_CREDITOS, 0)) "CARGA_CREDITOS"
FROM PROFESORES P, IMPARTIR I
WHERE P.ID = I.PROFESOR 
GROUP BY P.ID, P.NOMBRE, P.APELLIDO1
HAVING SUM(NVL(I.CARGA_CREDITOS, 0)) = 
    (SELECT MAX(SUM(NVL(IMP.CARGA_CREDITOS, 0)))
    FROM IMPARTIR IMP
    GROUP BY IMP.PROFESOR);

--13
SELECT D.CODIGO, D.NOMBRE, COUNT(*) "ASIGNATURAS"
FROM DEPARTAMENTOS D, ASIGNATURAS A
WHERE D.CODIGO = A.DEPARTAMENTO
GROUP BY D.CODIGO, D.NOMBRE
HAVING COUNT(*) = 
    (SELECT MAX(COUNT(*))
    FROM ASIGNATURAS ASIG
    GROUP BY ASIG.DEPARTAMENTO);

--14
SELECT P.ID, SUM(I.CARGA_CREDITOS)
FROM PROFESORES P, IMPARTIR I
WHERE P.ID = I.PROFESOR
GROUP BY P.ID
HAVING SUM(I.CARGA_CREDITOS) < 10;

--15
SELECT P.ID, SUM(I.CARGA_CREDITOS) "CARGA_CREDITOS"
FROM PROFESORES P, IMPARTIR I
WHERE P.ID = I.PROFESOR
GROUP BY P.ID
HAVING SUM(I.CARGA_CREDITOS) >
    (SELECT AVG(SUM(IMP.CARGA_CREDITOS))
    FROM IMPARTIR IMP
    GROUP BY IMP.PROFESOR);
    
--16
SELECT PRO.ID, PRO.NOMBRE, COUNT(*) "ASIGNATURAS"
FROM PROFESORES PRO, IMPARTIR IMP
WHERE PRO.ID = IMP.PROFESOR AND IMP.CURSO = '22/23'
GROUP BY PRO.ID, PRO.NOMBRE
HAVING COUNT(*) >= 2 AND SUM(IMP.CARGA_CREDITOS) < 6.5 * COUNT(*);

--17
SELECT A.NOMBRE
FROM ASIGNATURAS A
WHERE A.CODIGO NOT IN
(SELECT DISTINCT A2.CODIGO
FROM MATRICULAR M, ASIGNATURAS A2
WHERE DECODE(M.CALIFICACION, 'MH', 10, 'SB', 9, 'NT', 7, 'AP', 5, 'SP', 3, 'NP', 0, 0) >= 5
AND M.ASIGNATURA = A2.CODIGO);

--18
SELECT *
FROM DEPARTAMENTOS D
WHERE D.CODIGO NOT IN 
(SELECT DISTINCT A.DEPARTAMENTO
FROM ASIGNATURAS A
WHERE A.CREDITOS > 6);

--19
SELECT P.NOMBRE, P.APELLIDO1, P.APELLIDO2
FROM PROFESORES P, IMPARTIR I, ASIGNATURAS ASIG
WHERE P.ID = I.PROFESOR AND I.ASIGNATURA = ASIG.CODIGO AND UPPER(ASIG.CARACTER) = 'OP'
    AND (P.ID, I.GRUPO, I.CURSO, I.ASIGNATURA) NOT IN
    (SELECT P2.ID, I2.GRUPO, I2.CURSO, I2.ASIGNATURA
    FROM PROFESORES P2, IMPARTIR I2, MATRICULAR M, ASIGNATURAS ASIG2
    WHERE P2.ID = I2.PROFESOR AND I2.GRUPO = M.GRUPO AND I2.CURSO = M.CURSO AND I2.ASIGNATURA = M.ASIGNATURA AND I2.ASIGNATURA = ASIG2.CODIGO AND UPPER(ASIG2.CARACTER) = 'OP'
    GROUP BY P2.ID, I2.GRUPO, I2.CURSO, I2.ASIGNATURA);

--20
SELECT P3.NOMBRE || ' ' || P3.APELLIDO1 "PROFESOR1", P4.NOMBRE || ' ' || P4.APELLIDO1 "PROFESOR2"
FROM PROFESORES P3, PROFESORES P4
WHERE P3.ID < P4.ID AND (P3.ID, P4.ID) NOT IN 
    (SELECT DISTINCT P1.ID, P2.ID
    FROM PROFESORES P1, PROFESORES P2, IMPARTIR I1, MATRICULAR M1
    WHERE P1.ID < P2.ID AND P1.ID = I1.PROFESOR 
        AND I1.ASIGNATURA = M1.ASIGNATURA
        AND I1.CURSO = M1.CURSO
        AND I1.GRUPO = M1.GRUPO
        AND M1.ALUMNO IN
            (SELECT M2.ALUMNO
            FROM MATRICULAR M2, IMPARTIR I2
            WHERE P2.ID = I2.PROFESOR
            AND I2.ASIGNATURA = M2.ASIGNATURA
            AND I2.CURSO = M2.CURSO
            AND I2.GRUPO = M2.GRUPO
            ));

--21
SELECT P3.NOMBRE || ' ' || P3.APELLIDO1 "PROFESOR1", P4.NOMBRE || ' ' || P4.APELLIDO1 "PROFESOR2"
FROM PROFESORES P3, PROFESORES P4
WHERE P3.ID < P4.ID AND (P3.ID, P4.ID) NOT IN
    (SELECT DISTINCT P1.ID, P2.ID
    FROM PROFESORES P1, PROFESORES P2, IMPARTIR I
    WHERE P1.ID < P2.ID AND P1.ID = I.PROFESOR AND I.ASIGNATURA IN 
        (SELECT DISTINCT I2.ASIGNATURA
        FROM IMPARTIR I2
        WHERE P2.ID = I2.PROFESOR));

--22
SELECT ASIG.NOMBRE
FROM ASIGNATURAS ASIG 
WHERE ASIG.CODIGO NOT IN 
    (SELECT DISTINCT M.ASIGNATURA
    FROM ALUMNOS A, MATRICULAR M
    WHERE A.DNI = M.ALUMNO
    GROUP BY M.ASIGNATURA, A.CMUN
    HAVING COUNT(*) > 1);

--23
SELECT DISTINCT A.DNI
FROM ALUMNOS A, MATRICULAR MAT
WHERE A.DNI = MAT.ALUMNO
AND A.DNI NOT IN
(SELECT M.ALUMNO
FROM MATRICULAR M, IMPARTIR I, PROFESORES P
WHERE M.ASIGNATURA = I.ASIGNATURA AND I.PROFESOR = P.ID
AND P.FECHA_NACIMIENTO <= ALL
(SELECT P2.FECHA_NACIMIENTO
FROM PROFESORES P2));

--24
SELECT AL.*
FROM
(SELECT M.ALUMNO, COUNT(*) ASIGNATURAS
FROM MATRICULAR M
GROUP BY M.ALUMNO) AUX,
ALUMNOS AL
WHERE AL.DNI = AUX.ALUMNO AND AUX.ASIGNATURAS > 2 
    AND AUX.ALUMNO NOT IN
    (SELECT M2.ALUMNO
    FROM MATRICULAR M2, IMPARTIR I, PROFESORES P, DEPARTAMENTOS D
    WHERE M2.ASIGNATURA = I.ASIGNATURA AND I.PROFESOR = P.ID AND P.DEPARTAMENTO = D.CODIGO AND UPPER(D.NOMBRE) = 'MATEMATICA APLICADA');

--Alumnos y su numeros de asignaturas
SELECT M.ALUMNO, COUNT(*) ASIGNATURAS
FROM MATRICULAR M
GROUP BY M.ALUMNO;

--Alumnos que recibe clase de profesores del departamento de M.A.
SELECT DISTINCT M2.ALUMNO, P.NOMBRE, D.NOMBRE
    FROM MATRICULAR M2, IMPARTIR I, PROFESORES P, DEPARTAMENTOS D
    WHERE M2.ASIGNATURA = I.ASIGNATURA AND I.PROFESOR = P.ID AND P.DEPARTAMENTO = D.CODIGO AND UPPER(D.NOMBRE) = 'MATEMATICA APLICADA';

--25 WIP
SELECT AUX.DEPARTAMENTO, ASIG.NOMBRE, ASIG.CREDITOS
FROM 
(SELECT A.DEPARTAMENTO, MAX(A.CREDITOS) "CREDITOS"
FROM PROFESORES P, IMPARTIR I, ASIGNATURAS A
WHERE P.ID = I.PROFESOR AND I.ASIGNATURA = A.CODIGO AND P.FECHA_NACIMIENTO > TO_DATE('01/01/1970', 'dd/mm/yyyy')
GROUP BY A.DEPARTAMENTO) AUX,
ASIGNATURAS ASIG
WHERE ASIG.DEPARTAMENTO = AUX.DEPARTAMENTO AND ASIG.CREDITOS = AUX.CREDITOS;

--26
SELECT D.CODIGO, D.NOMBRE, CRED.TOTAL "CARGA CREDITOS"
FROM
(SELECT A.DEPARTAMENTO
FROM MATRICULAR M, ASIGNATURAS A
WHERE M.ASIGNATURA = A.CODIGO
GROUP BY A.DEPARTAMENTO
HAVING COUNT(DISTINCT M.ALUMNO) > 10) GT,
(SELECT A.DEPARTAMENTO, SUM(A.CREDITOS) "TOTAL"
FROM ASIGNATURAS A
GROUP BY A.DEPARTAMENTO) CRED,
DEPARTAMENTOS D
WHERE D.CODIGO = GT.DEPARTAMENTO AND GT.DEPARTAMENTO = CRED.DEPARTAMENTO
ORDER BY CRED.TOTAL;

--27
SELECT P.ID ,COUNT(*)
FROM MATRICULAR M, IMPARTIR I, PROFESORES P
WHERE M.ASIGNATURA = I.ASIGNATURA AND M.CURSO = I.CURSO AND M.GRUPO = I.GRUPO AND I.PROFESOR = P.ID AND P.ID IN
(SELECT DISTINCT P2.ID
FROM PROFESORES P2, IMPARTIR I2, ASIGNATURAS A
WHERE P2.ID = I2.PROFESOR AND I2.ASIGNATURA = A.CODIGO AND A.PRACTICOS > A.TEORICOS)
GROUP BY P.ID;

--28 
SELECT ASIG.NOMBRE, AL.NOMBRE, AL.APELLIDO1, AL.FECHA_PRIM_MATRICULA
FROM ALUMNOS AL, MATRICULAR M, ASIGNATURAS ASIG
WHERE AL.DNI = M.ALUMNO AND M.ASIGNATURA = ASIG.CODIGO AND M.CURSO = '20/21'
AND (M.ASIGNATURA, AL.FECHA_PRIM_MATRICULA) IN
    (SELECT M2.ASIGNATURA, MIN(AL2.FECHA_PRIM_MATRICULA)
    FROM ALUMNOS AL2, MATRICULAR M2
    WHERE AL2.DNI = M2.ALUMNO AND M2.CURSO = '20/21'
    GROUP BY M2.ASIGNATURA
    HAVING COUNT(*) > 3);
    
SELECT M.ASIGNATURA, AL.NOMBRE, AL.APELLIDO1, AL.FECHA_PRIM_MATRICULA
FROM MATRICULAR M, ALUMNOS AL
WHERE M.ALUMNO = AL.DNI AND M.CURSO = '20/21';
    
--29
SELECT ASIG2.NOMBRE, COUNT(I.ASIGNATURA)
FROM ASIGNATURAS ASIG2 LEFT OUTER JOIN IMPARTIR I ON(ASIG2.CODIGO = I.ASIGNATURA)
WHERE (I.CURSO = '21/22' OR I.CURSO IS NULL)
AND ASIG2.CODIGO IN 
    --ASIGNATURAS CON MENOS DE 16 ALUMNOS
    (SELECT M.ASIGNATURA
    FROM MATRICULAR M, ASIGNATURAS ASIG
    WHERE M.ASIGNATURA = ASIG.CODIGO AND M.CURSO = '21/22'
    AND ASIG.DEPARTAMENTO IN 
        --DEPARTAMENTO MAS ANTIGUO
        (SELECT CODIGO
        FROM DEPARTAMENTOS D
        WHERE D.FECHA_CREACION <= ALL
            (SELECT D2.FECHA_CREACION
            FROM DEPARTAMENTOS D2))
    GROUP BY M.ASIGNATURA
    HAVING COUNT(*) < 16)
GROUP BY ASIG2.NOMBRE;

--30
SELECT I.PROFESOR
FROM IMPARTIR I
WHERE EXISTS
    (SELECT *
    FROM MATRICULAR M, IMPARTIR I2
    WHERE I2.PROFESOR = I.PROFESOR 
    AND M.CURSO = I2.CURSO 
    AND M.ASIGNATURA = I2.ASIGNATURA
    AND M.GRUPO = I2.GRUPO
    AND M.ALUMNO IN 
        (SELECT AL.DNI
        FROM ALUMNOS AL
        WHERE AL.DNI = M.ALUMNO
        AND AL.FECHA_NACIMIENTO < '01/01/2001'))
GROUP BY I.PROFESOR
HAVING COUNT(*) >= 2;

SELECT I.PROFESOR
FROM MATRICULAR M, IMPARTIR I
WHERE M.CURSO = I.CURSO 
AND M.ASIGNATURA = I.ASIGNATURA
AND M.GRUPO = I.GRUPO
AND M.ALUMNO IN 
    (SELECT AL.DNI
    FROM ALUMNOS AL
    WHERE AL.DNI = M.ALUMNO
    AND AL.FECHA_NACIMIENTO < '01/01/2001')
GROUP BY I.PROFESOR;


