CREATE TABLE MISALUMNOS (
"DNI" NUMBER(9,0) PRIMARY KEY,
"NOMBRE" VARCHAR2(20 BYTE),
"APELLIDO1" VARCHAR2(20 BYTE),
"APELLIDO2" VARCHAR2(20 BYTE),
"GENERO" VARCHAR2(4 BYTE),
"EMAIL" VARCHAR2(40 BYTE),
"FECHA_NACIMIENTO" DATE,
"FECHA_PRIM_MATRICULA" DATE
);


--1
INSERT INTO MISALUMNOS
SELECT DNI, A.NOMBRE, APELLIDO1, APELLIDO2, GENERO, EMAIL, FECHA_NACIMIENTO, FECHA_PRIM_MATRICULA 
FROM DOCENCIA.ALUMNOS A, DOCENCIA.PROVINCIA P
WHERE A.CPRO = P.CODIGO AND P.NOMBRE = 'Málaga';

--2
UPDATE MISALUMNOS
SET NOMBRE = UPPER(NOMBRE), APELLIDO1 = UPPER(APELLIDO1), APELLIDO2 = UPPER(APELLIDO2);

--3
CREATE TABLE MIMATRICULAR AS SELECT * FROM DOCENCIA.MATRICULAR;

--4
DELETE FROM MIMATRICULAR
WHERE ALUMNO NOT IN 
    (SELECT DNI
    FROM MISALUMNOS);
    
--5
INSERT INTO MIMATRICULAR(alumno, asignatura, grupo, curso) 
    SELECT DNI, 112, 'A', '23/24'
    FROM MISALUMNOS
    WHERE MONTHS_BETWEEN(SYSDATE, FECHA_PRIM_MATRICULA)/12 < 4 AND DNI NOT IN
        (SELECT M.ALUMNO
        FROM MIMATRICULAR M
        WHERE M.ASIGNATURA = 112
        AND M.CALIFICACION IN ('MH', 'NT', 'AP', 'SB'));
        
--6
UPDATE MIMATRICULAR
SET CALIFICACION = 'NP' 
WHERE CURSO < '23/24' AND CALIFICACION IS NULL;

--7
UPDATE MIMATRICULAR
SET CALIFICACION = 'AP'
WHERE CURSO < '23/24' AND CALIFICACION IN ('SP', 'NP') AND ALUMNO IN
    (SELECT M.ALUMNO
    FROM MIMATRICULAR M
    WHERE M.CURSO < '23/24' AND M.CALIFICACION IN ('SP', 'NP')
    GROUP BY M.ALUMNO
    HAVING COUNT(*) = 1);
    
--8
SELECT M.ALUMNO, A.CURSO, COUNT(*)
FROM MIMATRICULAR M, DOCENCIA.ASIGNATURAS A
WHERE M.ASIGNATURA = A.CODIGO AND M.CALIFICACION NOT IN ('SP', 'NP') AND A.CURSO IS NOT NULL AND A.CURSO < 3
GROUP BY M.ALUMNO, A.CURSO;

