--1
CREATE TABLE TOUR AS SELECT * FROM DOCENCIA.TOUR2017;

--2
CREATE TABLE INFO_PERSONAL AS SELECT ID, NAME NOMBRE, NATIONALITY NACIONALIDAD FROM TOUR;
ALTER TABLE INFO_PERSONAL ADD PRIMARY KEY (ID);

CREATE TABLE INFO_PROFESIONAL AS SELECT ID, TEAM EQUIPO, COUNTRY PAIS, CATEGORY CATEGORIA FROM TOUR;
ALTER TABLE INFO_PROFESIONAL ADD PRIMARY KEY (ID);

--3
CREATE VIEW TOUR_VIEW AS
SELECT PER.ID, PRO.EQUIPO, PRO.PAIS, PER.NOMBRE, PER.NACIONALIDAD, PRO.CATEGORIA
FROM INFO_PERSONAL PER, INFO_PROFESIONAL PRO
WHERE PER.ID = PRO.ID;

SELECT * FROM TOUR;
SELECT * FROM TOUR_VIEW;

INSERT INTO TOUR VALUES(500, 'UMA INFORMATICA', 'ESPAÑA', 'ENRIQUE SOLER', 'ESP', 'WORLDTOUR');
INSERT INTO TOUR_VIEW VALUES(500, 'UMA INFORMATICA', 'ESPAÑA', 'ENRIQUE SOLER', 'ESP', 'WORLDTOUR');

CREATE OR REPLACE TRIGGER TR_INSERTA_CICLISTA
INSTEAD OF INSERT ON TOUR_VIEW
FOR EACH ROW
BEGIN
    INSERT INTO INFO_PERSONAL VALUES (:NEW.ID, :NEW.NOMBRE, :NEW.NACIONALIDAD);
    INSERT INTO INFO_PROFESIONAL VALUES (:NEW.ID, :NEW.EQUIPO, :NEW.PAIS, :NEW.CATEGORIA);
END;


