--1
CREATE TABLE TOUR AS SELECT * FROM DOCENCIA.TOUR2017;

--2
CREATE TABLE INFO_PERSONAL AS SELECT ID, NAME NOMBRE, NATIONALITY NACIONALIDAD FROM TOUR;
ALTER TABLE INFO_PERSONAL ADD PRIMARY KEY (ID);

CREATE TABLE INFO_PROFESIONAL AS SELECT ID, TEAM EQUIPO, COUNTRY PAIS, CATEGORY CATEGORIA FROM TOUR;
ALTER TABLE INFO_PROFESIONAL ADD PRIMARY KEY (ID);

--3
CREATE VIEW TOUR_VIEW AS
SELECT PER.ID, PRO.EQUIPO, PRO.PAIS, PER.NOMBRE, PER.NACIONALIDAD, PRO.CATEGORIA
FROM INFO_PERSONAL PER, INFO_PROFESIONAL PRO
WHERE PER.ID = PRO.ID;

SELECT * FROM TOUR;
SELECT * FROM TOUR_VIEW;

--4
INSERT INTO TOUR VALUES(500, 'UMA INFORMATICA', 'ESPA�A', 'ENRIQUE SOLER', 'ESP', 'WORLDTOUR');
INSERT INTO TOUR_VIEW VALUES(500, 'UMA INFORMATICA', 'ESPA�A', 'ENRIQUE SOLER', 'ESP', 'WORLDTOUR');

CREATE OR REPLACE TRIGGER TR_INSERTA_CICLISTA
INSTEAD OF INSERT ON TOUR_VIEW
FOR EACH ROW
BEGIN
    INSERT INTO INFO_PERSONAL VALUES (:NEW.ID, :NEW.NOMBRE, :NEW.NACIONALIDAD);
    INSERT INTO INFO_PROFESIONAL VALUES (:NEW.ID, :NEW.EQUIPO, :NEW.PAIS, :NEW.CATEGORIA);
END;

--5
CREATE TABLE LOG_INSERCION(
    USUARIO VARCHAR2(30),
    FECHA DATE
);

CREATE OR REPLACE TRIGGER TOUR_INSRCION
AFTER INSERT ON TOUR
BEGIN
    INSERT INTO LOG_INSERCION VALUES (USER, SYSDATE);
END;

--6
CREATE VIEW TOUR_SPAIN AS
SELECT *
FROM tour_view T
WHERE UPPER(T.NACIONALIDAD) = 'ESP';

CREATE VIEW TOUR_ITALY AS
SELECT *
FROM tour_view T
WHERE UPPER(T.NACIONALIDAD) = 'ITA';

--7
INSERT INTO TOUR_SPAIN VALUES (501, 'UMA INFORMATICA', 'ESPAÑA', 'ENRIQUE SOLER', 'ESP', 'WORLDTOUR');

--8 Puedo insertar a trav�s de la vista pero no puedo ver el dato insertado pues no es de nacionalidad espa�ola
INSERT INTO TOUR_SPAIN VALUES (502, 'UMA INFORMATICA', 'ESPAÑA', 'ENRIQUE SOLER', 'ITA', 'WORLDTOUR');

--9
CREATE OR REPLACE VIEW TOUR_SPAIN AS
SELECT *
FROM tour_view T
WHERE UPPER(T.NACIONALIDAD) = 'ESP'
WITH CHECK OPTION;

INSERT INTO TOUR_SPAIN VALUES (504, 'UMA INFORMATICA', 'ESPAÑA', 'ENRIQUE SOLER', 'ITA', 'WORLDTOUR');

--11
CREATE OR REPLACE VIEW TOUR_SPAIN AS
SELECT *
FROM tour_view T
WHERE UPPER(T.NACIONALIDAD) = 'ESP'
WITH READ ONLY;

INSERT INTO TOUR_SPAIN VALUES (505, 'UMA INFORMATICA', 'ESPAÑA', 'ENRIQUE SOLER', 'ESP', 'WORLDTOUR');

--12
CREATE OR REPLACE VIEW V_TOUR_FRANCE AS
SELECT *
FROM tour_view T
WHERE UPPER(T.NACIONALIDAD) = 'FRA';

GRANT DELETE ON V_TOUR_FRANCE TO UBD1005;

--14
CREATE VIEW CICLISTAS_POR_EQUIPOS AS    
    SELECT EQUIPO "NOMBRE", COUNT(*) "NUM_CICLISTAS"
    FROM TOUR_VIEW
    GROUP BY EQUIPO;