--1
SELECT A1.NOMBRE "NOMBRE1", A1.APELLIDO1 "APELLIDO1_1", A1.APELLIDO2 "APELLIDO1_2", A2.NOMBRE "NOMBRE2", A2.APELLIDO1 "APELLIDO2_1", A2.APELLIDO2 "APELLIDO2_2"
FROM ALUMNOS A1, ALUMNOS A2
WHERE A1.DNI < A2.DNI AND A1.CPRO != 29 AND A1.CPRO = A2.CPRO;

--2
SELECT AL.NOMBRE "Nombre", AL.APELLIDO1 || ' ' || AL.APELLIDO2 "APELLIDOS", NVL(ASIG.NOMBRE, 'No Matriculado') "NOMBREASIGNATURA", NVL(M.CURSO, 'No Matriculado') "CURSO"
FROM ALUMNOS AL LEFT OUTER JOIN (MATRICULAR M JOIN ASIGNATURAS ASIG ON (M.ASIGNATURA = ASIG.CODIGO)) ON (AL.DNI = M.ALUMNO);

--3
SELECT ID
    FROM
    (SELECT P.ID, COUNT(*) "SOBRESALIENTES"
    FROM PROFESORES P, IMPARTIR I, MATRICULAR M
    WHERE P.ID = I.PROFESOR AND I.CURSO = M.CURSO AND I.GRUPO = M.GRUPO AND I.ASIGNATURA = M.ASIGNATURA AND M.CALIFICACION = 'SB'
    GROUP BY P.ID
    ORDER BY COUNT(*) DESC)
WHERE ROWNUM < 2;

SELECT *
    FROM PROFESORES P, IMPARTIR I, MATRICULAR M
    WHERE P.ID = I.PROFESOR AND I.CURSO = M.CURSO AND I.GRUPO = M.GRUPO AND I.ASIGNATURA = M.ASIGNATURA AND M.CALIFICACION = 'SB';

--4
SELECT TO_CHAR(AL.FECHA_NACIMIENTO, 'yyyy') "AÑO", TO_CHAR(AL.FECHA_NACIMIENTO, 'MONTH') "MES", COUNT(*) "NUMERO_ALUMNOS"
FROM ALUMNOS AL
WHERE AL.FECHA_NACIMIENTO IS NOT NULL
GROUP BY TO_CHAR(AL.FECHA_NACIMIENTO, 'yyyy'), TO_CHAR(AL.FECHA_NACIMIENTO, 'MONTH');

--5
SELECT DISTINCT A.NOMBRE, A.APELLIDO1, A.APELLIDO2
FROM ALUMNOS A, MATRICULAR M, ASIGNATURAS ASIG 
WHERE A.DNI = M.ALUMNO AND M.ASIGNATURA = ASIG.CODIGO AND ASIG.CURSO = 3
AND A.DNI NOT IN 
    (SELECT A1.DNI
    FROM ALUMNOS A1, MATRICULAR M1, ASIGNATURAS ASIG1
    WHERE A1.DNI = M1.ALUMNO AND M1.ASIGNATURA = ASIG1.CODIGO AND ASIG1.CURSO = 1 AND M1.CALIFICACION IN ('MH', 'SB', 'NT', 'AP'))
AND A.DNI NOT IN
    (SELECT A2.DNI
    FROM ALUMNOS A2, MATRICULAR M2, ASIGNATURAS ASIG2
    WHERE A2.DNI = M2.ALUMNO AND M2.ASIGNATURA = ASIG2.CODIGO AND ASIG2.CURSO = 2 AND M2.CALIFICACION IN ('MH', 'SB', 'NT', 'AP'));
