@Ejer 1
SELECT COUNT(*), DEPARTAMENTOS.NOMBRE
FROM PROFESORES, DEPARTAMENTOS
WHERE PROFESORES.DEPARTAMENTO = DEPARTAMENTOS.CODIGO
GROUP BY DEPARTAMENTOS.NOMBRE;

@Ejer 2
SELECT SUM(CREDITOS), DEPARTAMENTO
FROM ASIGNATURAS 
GROUP BY DEPARTAMENTO;

@Ejer 3
SELECT COUNT(DISTINCT ALUMNO)
FROM MATRICULAR
GROUP BY MATRICULAR.CURSO;

@Ejer 4
SELECT SUM(IMPARTIR.CARGA_CREDITOS), DESPACHO
FROM PROFESORES, IMPARTIR
WHERE PROFESORES.ID = IMPARTIR.PROFESOR
AND PROFESORES.DESPACHO IS NOT NULL
GROUP BY DESPACHO;

@Ejer 5
SELECT ROUND(COUNT(NULLIF(GENERO, 'MASC'))/COUNT(ALUMNO), 2) "PORCENTAJE", ASIGNATURA
FROM MATRICULAR, ALUMNOS
WHERE ALUMNOS.DNI = MATRICULAR.ALUMNO
GROUP BY MATRICULAR.ASIGNATURA;


@Ejer 6
SELECT PROVINCIA.NOMBRE, SUM(HOMBRES+MUJERES)"POBLACION"
FROM MUNICIPIO, PROVINCIA
WHERE MUNICIPIO.CPRO = PROVINCIA.CODIGO
GROUP BY PROVINCIA.NOMBRE;

@##################
@PARTE 2          #
@##################


@Ejer 7
SELECT PROFESORES.NOMBRE, PROFESORES.APELLIDO1, PROFESORES.APELLIDO2, PROFESORES.DEPARTAMENTO
FROM PROFESORES WHERE (PROFESORES.FECHA_NACIMIENTO, PROFESORES.DEPARTAMENTO) IN(
    SELECT MIN(PROFESORES.FECHA_NACIMIENTO), DEPARTAMENTO
    FROM PROFESORES
    GROUP BY DEPARTAMENTO
);

@Ejer 8
SELECT ASIGNATURAS.NOMBRE, MATRICULAR.ALUMNO 
FROM ASIGNATURAS, MATRICULAR
WHERE ASIGNATURAS.CODIGO = MATRICULAR.ASIGNATURA
AND (ASIGNATURAS.CREDITOS, MATRICULAR.ALUMNO) IN (
    SELECT MAX(ASIGNATURAS.CREDITOS), MATRICULAR.ALUMNO
    FROM MATRICULAR, ASIGNATURAS
    WHERE MATRICULAR.ASIGNATURA = ASIGNATURAS.CODIGO
    GROUP BY MATRICULAR.ALUMNO
);


@Ejer 9
SELECT *
FROM PROFESORES
WHERE (PROFESORES.FECHA_NACIMIENTO, DEPARTAMENTO) IN(
    SELECT MIN(PROFESORES.FECHA_NACIMIENTO), DEPARTAMENTO
    FROM PROFESORES
    GROUP BY DEPARTAMENTO
)
ORDER BY DEPARTAMENTO;


@Ejer 10
SELECT  ASIGNATURAS.DEPARTAMENTO,ASIGNATURAS.NOMBRE, ASIGNATURAS.CREDITOS
FROM ASIGNATURAS
WHERE (ASIGNATURAS.CREDITOS, ASIGNATURAS.DEPARTAMENTO)
IN (
    SELECT MIN(CREDITOS), DEPARTAMENTO
    FROM ASIGNATURAS
    GROUP BY DEPARTAMENTO
)
ORDER BY DEPARTAMENTO;

@Ejer 11
SELECT DISTINCT ALUMNOS.NOMBRE || ' ' || ALUMNOS.APELLIDO1 "NOMBRE ALUMNO", MATRICULAR.ASIGNATURA
FROM ALUMNOS, MATRICULAR
WHERE ALUMNOS.DNI = MATRICULAR.ALUMNO
AND (ALUMNOS.FECHA_NACIMIENTO, MATRICULAR.ASIGNATURA) IN (
    SELECT MIN(FECHA_NACIMIENTO), MATRICULAR.ASIGNATURA
    FROM ALUMNOS, MATRICULAR
    WHERE ALUMNOS.DNI = MATRICULAR.ALUMNO
    AND MATRICULAR.CURSO = '20/21'
    GROUP BY MATRICULAR.ASIGNATURA
);


@###################
@PARTE 3           #
@###################

@EJER 12
SELECT PROFESORES.NOMBRE, PROFESORES.APELLIDO1, SUM(CARGA_CREDITOS) "CREDITOS"
FROM PROFESORES, IMPARTIR 
WHERE PROFESORES.ID = IMPARTIR.PROFESOR
GROUP BY PROFESORES.ID, PROFESORES.NOMBRE, PROFESORES.APELLIDO1
HAVING SUM(CARGA_CREDITOS) = 
(SELECT MAX(SUM(CARGA_CREDITOS)) FROM IMPARTIR GROUP BY PROFESOR)
;



@Ejer 13
SELECT DEPARTAMENTOS.NOMBRE, COUNT(*) "NUMERO ASIGNATURAS"
FROM DEPARTAMENTOS, ASIGNATURAS
WHERE DEPARTAMENTOS.CODIGO = ASIGNATURAS.DEPARTAMENTO
GROUP BY DEPARTAMENTOS.CODIGO, DEPARTAMENTOS.NOMBRE
HAVING COUNT(*) = 
(SELECT MAX(COUNT(*)) FROM ASIGNATURAS GROUP BY ASIGNATURAS.DEPARTAMENTO);

@EJER 14
SELECT PROFESORES.ID, SUM(CARGA_CREDITOS)
FROM PROFESORES, IMPARTIR
WHERE PROFESORES.ID = IMPARTIR.PROFESOR
GROUP BY PROFESORES.ID
HAVING SUM(CARGA_CREDITOS) < 10;

@EJER 15
SELECT PROFESORES.NOMBRE || ' ' || PROFESORES.APELLIDO1 "Nombre"
FROM PROFESORES, IMPARTIR
WHERE PROFESORES.ID = IMPARTIR.PROFESOR
GROUP BY PROFESORES.ID, PROFESORES.NOMBRE, PROFESORES.APELLIDO1
HAVING SUM(CARGA_CREDITOS) >= (SELECT AVG(SUM(CARGA_CREDITOS)) FROM IMPARTIR GROUP BY IMPARTIR.PROFESOR);

@EJER 16
SELECT P.ID
FROM PROFESORES P, IMPARTIR
WHERE P.ID = IMPARTIR.PROFESOR
AND IMPARTIR.CURSO = '22/23'
GROUP BY P.ID
HAVING COUNT(DISTINCT IMPARTIR.ASIGNATURA) >=2 
AND 6.5 >= ALL(SELECT IMPARTIR.CARGA_CREDITOS FROM IMPARTIR WHERE IMPARTIR.CURSO = '22/23' AND IMPARTIR.PROFESOR = P.ID);


@##################
@PARTE 4          #
@##################


@EJER 17
SELECT ASIGNATURAS.NOMBRE 
FROM ASIGNATURAS
WHERE ASIGNATURAS.CODIGO NOT IN
(
SELECT DISTINCT MATRICULAR.ASIGNATURA
FROM MATRICULAR
WHERE CALIFICACION IN ('AP', 'MH', 'SB', 'NT')
);

@EJER 18
SELECT *
FROM DEPARTAMENTOS D
WHERE D.CODIGO NOT IN (
    SELECT DISTINCT ASIGNATURAS.DEPARTAMENTO
    FROM ASIGNATURAS
    WHERE ASIGNATURAS.CREDITOS > 6
);

@EJER 19
SELECT *
FROM PROFESORES
WHERE PROFESORES.ID IN (

SELECT DISTINCT IMPARTIR.PROFESOR
FROM IMPARTIR, ASIGNATURAS
WHERE IMPARTIR.ASIGNATURA = ASIGNATURAS.CODIGO
AND ASIGNATURAS.CARACTER = 'OP'
AND IMPARTIR.PROFESOR NOT IN 
(

SELECT DISTINCT IMPARTIR.PROFESOR
FROM IMPARTIR, ASIGNATURAS, MATRICULAR
WHERE IMPARTIR.ASIGNATURA = ASIGNATURAS.CODIGO
AND IMPARTIR.CURSO= MATRICULAR.CURSO
AND IMPARTIR.GRUPO = MATRICULAR.GRUPO
AND ASIGNATURAS.CARACTER = 'OP'

));


@Ejer 20
SELECT P3.NOMBRE || ' ' || P3.APELLIDO1 "NOMBRE 1", P4.NOMBRE || ' ' || P4.APELLIDO1 "nOMBRE 2"
FROM PROFESORES P3, PROFESORES P4
WHERE P3.ID < P4.ID
AND (P3.ID, P4.ID) NOT IN (
    SELECT DISTINCT P1.ID, P2.ID
    FROM PROFESORES P1, IMPARTIR I1, MATRICULAR M1, PROFESORES P2
    WHERE I1.CURSO = M1.CURSO
    AND I1.GRUPO = M1.GRUPO
    AND I1.ASIGNATURA = M1.ASIGNATURA
    AND P1.ID = I1.PROFESOR
    AND P1.ID < P2.ID
    AND M1.ALUMNO IN (
            SELECT M2.ALUMNO
            FROM IMPARTIR I2, MATRICULAR M2
            WHERE I2.CURSO = M2.CURSO
            AND I2.GRUPO = M2.GRUPO
            AND I2.ASIGNATURA = M2.ASIGNATURA
            AND P2.ID = I2.PROFESOR
    )
);



@EJER 21
SELECT P1.NOMBRE || ' ' || P1.APELLIDO1 "Profesor 1", P2.NOMBRE || ' ' || P2.APELLIDO1 "Profesor 2"
FROM PROFESORES P1, PROFESORES P2
WHERE P1.ID < P2.ID
AND ( P1.ID, P2.ID ) NOT IN 
(

SELECT DISTINCT P3.ID, P4.ID
FROM PROFESORES P3, IMPARTIR I1, PROFESORES P4
WHERE P3.ID < P4.ID
AND I1.PROFESOR = P3.ID
AND I1.ASIGNATURA IN (
    SELECT DISTINCT I2.ASIGNATURA
    FROM IMPARTIR I2
    WHERE I2.PROFESOR = P4.ID
)
);



@EJER 22
SELECT * 
FROM ASIGNATURAS
WHERE ASIGNATURAS.CODIGO NOT IN (
    SELECT DISTINCT MATRICULAR.ASIGNATURA
    FROM MATRICULAR, ALUMNOS
    WHERE MATRICULAR.ALUMNO = ALUMNOS.DNI
    GROUP BY MATRICULAR.ASIGNATURA, ALUMNOS.CMUN
    HAVING COUNT(*) = 2
);


@############################
@PARTE 5 (COMPLEMENTARIOS)  #
@############################


@EJER 23
SELECT DISTINCT ALUMNOS.DNI
FROM ALUMNOS, MATRICULAR
WHERE ALUMNOS.DNI = MATRICULAR.ALUMNO
AND MATRICULAR.ASIGNATURA NOT IN 
(

SELECT MATRICULAR.ASIGNATURA
FROM IMPARTIR, MATRICULAR
WHERE MATRICULAR.CURSO = IMPARTIR.CURSO
AND MATRICULAR.GRUPO = IMPARTIR.GRUPO
AND IMPARTIR.PROFESOR = (SELECT PROFESORES.ID FROM PROFESORES WHERE PROFESORES.FECHA_NACIMIENTO = (SELECT MIN(FECHA_NACIMIENTO) FROM PROFESORES))

);

@EJER 24
SELECT DISTINCT MATRICULAR.ALUMNO
FROM MATRICULAR 
WHERE (MATRICULAR.ASIGNATURA, MATRICULAR.GRUPO, MATRICULAR.CURSO) NOT IN (

    SELECT DISTINCT IMPARTIR.ASIGNATURA, IMPARTIR.GRUPO, IMPARTIR.CURSO
    FROM IMPARTIR
    WHERE IMPARTIR.PROFESOR IN (
    
        SELECT PROFESORES.ID
        FROM PROFESORES, DEPARTAMENTOS
        WHERE PROFESORES.DEPARTAMENTO = DEPARTAMENTOS.CODIGO
        AND UPPER(DEPARTAMENTOS.NOMBRE) = 'MATEMATICA APLICADA'
    
    )

)
GROUP BY MATRICULAR.ALUMNO
HAVING COUNT(DISTINCT MATRICULAR.ASIGNATURA) > 2
;

@EJER 25
SELECT ASIGNATURAS.NOMBRE, ASIGNATURAS.DEPARTAMENTO, ASIGNATURAS.CREDITOS
FROM ASIGNATURAS WHERE (ASIGNATURAS.CREDITOS, ASIGNATURAS.DEPARTAMENTO) IN
(
SELECT MAX(CREDITOS), DEPARTAMENTO
FROM ASIGNATURAS
WHERE ASIGNATURAS.CODIGO NOT IN (
    SELECT IMPARTIR.ASIGNATURA
    FROM IMPARTIR, PROFESORES
    WHERE IMPARTIR.PROFESOR = PROFESORES.ID
    AND PROFESORES.FECHA_NACIMIENTO < '01/01/1970'
)
GROUP BY DEPARTAMENTO
)

ORDER BY DEPARTAMENTO;

@EJER 26
SELECT SUM(ASIGNATURAS.CREDITOS) "Carga Creditos", DEPARTAMENTO
FROM DEPARTAMENTOS, ASIGNATURAS
WHERE DEPARTAMENTOS.CODIGO = ASIGNATURAS.DEPARTAMENTO
AND DEPARTAMENTOS.CODIGO IN 
(
    SELECT DISTINCT ASIGNATURAS.DEPARTAMENTO
    FROM ASIGNATURAS
    WHERE ASIGNATURAS.CODIGO IN (
        SELECT DISTINCT ASIGNATURAS.CODIGO
        FROM MATRICULAR, ASIGNATURAS
        WHERE MATRICULAR.ASIGNATURA = ASIGNATURAS.CODIGO
        GROUP BY ASIGNATURAS.CODIGO
        HAVING (COUNT(DISTINCT MATRICULAR.ALUMNO)) > 10
    )

)
GROUP BY DEPARTAMENTO
ORDER BY "Carga Creditos" DESC;

@EJER 27
SELECT IMPARTIR.PROFESOR, COUNT(MATRICULAR.ALUMNO) "Alumnos"
FROM IMPARTIR, MATRICULAR
WHERE IMPARTIR.CURSO = MATRICULAR.CURSO
AND IMPARTIR.GRUPO = MATRICULAR.GRUPO
AND IMPARTIR.PROFESOR IN
(

    SELECT DISTINCT IMPARTIR.PROFESOR
    FROM IMPARTIR
    WHERE IMPARTIR.ASIGNATURA IN (
        SELECT ASIGNATURAS.CODIGO
        FROM ASIGNATURAS 
        WHERE PRACTICOS > TEORICOS
    )

)
GROUP BY IMPARTIR.PROFESOR;

@EJER 28
SELECT ALUMNOS.NOMBRE || ' ' || ALUMNOS.APELLIDO1 "Nombre", MATRICULAR.ASIGNATURA "Asignatura", ALUMNOS.FECHA_PRIM_MATRICULA
FROM MATRICULAR, ALUMNOS
WHERE MATRICULAR.ALUMNO = ALUMNOS.DNI
AND (ALUMNOS.FECHA_PRIM_MATRICULA, MATRICULAR.ASIGNATURA) IN 
(
    SELECT MIN(ALUMNOS.FECHA_PRIM_MATRICULA), MATRICULAR.ASIGNATURA
    FROM ALUMNOS, MATRICULAR
    WHERE ALUMNOS.DNI = MATRICULAR.ALUMNO
    AND MATRICULAR.ASIGNATURA IN 
    (
        SELECT MATRICULAR.ASIGNATURA
        FROM MATRICULAR
        WHERE MATRICULAR.CURSO = '20/21'
        GROUP BY MATRICULAR.ASIGNATURA
        HAVING COUNT(MATRICULAR.ALUMNO) > 3 
    )
    GROUP BY MATRICULAR.ASIGNATURA
);


@EJER 29
SELECT ASIGNATURAS.CODIGO, ASIGNATURAS.NOMBRE, COUNT(DISTINCT IMPARTIR.PROFESOR)
FROM ASIGNATURAS LEFT OUTER JOIN IMPARTIR ON(IMPARTIR.ASIGNATURA = ASIGNATURAS.CODIGO)
WHERE (IMPARTIR.CURSO = '21/22' OR IMPARTIR.CURSO IS NULL)
AND ASIGNATURAS.CODIGO IN 
(
    SELECT MATRICULAR.ASIGNATURA
    FROM MATRICULAR, ASIGNATURAS
    WHERE MATRICULAR.CURSO = '21/22'
    AND MATRICULAR.ASIGNATURA = ASIGNATURAS.CODIGO
    AND ASIGNATURAS.DEPARTAMENTO = 
    (    
        SELECT DEPARTAMENTOS.CODIGO 
        FROM DEPARTAMENTOS
        WHERE DEPARTAMENTOS.FECHA_CREACION = 
        (  
            SELECT MIN(FECHA_CREACION)
            FROM DEPARTAMENTOS
        )
    )
    GROUP BY MATRICULAR.ASIGNATURA
    HAVING COUNT(MATRICULAR.ALUMNO) < 16
)
GROUP BY ASIGNATURAS.CODIGO, ASIGNATURAS.NOMBRE
;

@EJER 30
SELECT IMPARTIR.PROFESOR
FROM IMPARTIR
GROUP BY IMPARTIR.PROFESOR
HAVING COUNT(DISTINCT IMPARTIR.ASIGNATURA) >= 2

INTERSECT

SELECT DISTINCT IMPARTIR.PROFESOR
FROM IMPARTIR, MATRICULAR, ALUMNOS
WHERE IMPARTIR.CURSO = MATRICULAR.CURSO
AND IMPARTIR.GRUPO = MATRICULAR.GRUPO
AND MATRICULAR.ALUMNO = ALUMNOS.DNI
AND ALUMNOS.FECHA_NACIMIENTO < '01/01/2001';











